### PR TITLE
Don't use deprecated DefaultHttpClient

### PR DESCRIPTION
**Pull request by dpursehouse**
Change-Id: I73464cae3d5b959e42a2575c4eaa70a178e9cf85

### CODE REVIEW

**Comment by rsandell** [comment]
Looks OK, just want to hold off merging untill we've figure out how to handle the current -beta release.

**Comment by dpursehouse** [comment]
Looks like this breaks the tests.  Hold off on merging this until I've investigated...

**Comment by dpursehouse** [comment]
Tests are passing locally...

**Comment by rsandell** [comment]
Yes ```BackCompat252HudsonTest``` tends to hang every now and then. I haven't manage to fix it and I don't dare to remove it either since it contains some important tests.

**Comment by rsandell** [comment]
:+1: But holding off the merge untill We've figure out how to handle the current -beta release

**Pull request merged**
