### PR TITLE
Fixing JENKINS-20808 by escaping single quotes inside BUILDS_STATS

### PR DESCRIPTION
**Pull request by ssbarnea**
This should fix https://issues.jenkins-ci.org/browse/JENKINS-20808 which was reported multiple times.

### CODE REVIEW

**Comment by ssbarnea** [comment]
@rsandell Can you have a look at this? It should solve a bug that is more than 3 years old.

**Comment by rsandell** [comment]
Well, the big question and why it probably hasn't been tackled before is if this also works on windows or if it will break even more.

**Comment by josselinchevalay** [comment]
hello, 

do you have an ETA when that can enable into plugin ? 

Regards

**Comment by rsandell** [comment]
Still waiting for a response to my inquiry.

**Comment by florent-vial** [comment]
@ssbarnea can you test it on windows?
This bug is annoying and creating a lot of confusion for developers.
I would expect > 90% users have their Jenkins server run on linux anyway

**Comment by ssbarnea** [comment]
@florent-vial Sorry but the answer is no. I don't have a Windows machine, last time I had one was more than an year ago. It would just take too much time to deploy one. If someone can share one with Jenkins I would not mind helping.

**Comment by florent-vial** [comment]
@rsandell cannot the automated test suite be enhanced ? Thinking of https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fgerrit-trigger-plugin/detail/PR-307/4/pipeline here

**Comment by florent-vial** [comment]
I abandoned installing JDK8 on my windows 10 machine for building the plugin after reading this thread https://community.oracle.com/thread/3825840.
So i did the following:
 *  downloaded the fix using:
`git clone https://github.com/jenkinsci/gerrit-trigger-plugin.git && cd gerrit-trigger-plugin && git fetch origin refs/pull/307/head:fix_quote && git checkout fix_quote`

git log -1 shows 
`commit d1bcbbae836434d1a1553f234e7fe4d24d4cb3ff (HEAD -> fix_quote)
Author: Sorin Sbarnea <ssbarnea@redhat.com>
Date:   Thu Jan 19 13:37:40 2017 +0000

    Fixing JENKINS-20808 by escaping single quotes inside BUILDS_STATS message.`

* compiled the plugin on Ubuntu using java 1.8.0.121 `mvn clean package`. Result was:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29:18.291s
[INFO] Finished at: Tue Sep 19 19:45:19 CEST 2017
[INFO] Final Memory: 122M/5487M
[INFO] ------------------------------------------------------------------------
 * install Jenkins 2.73.1 on my Windows 10 machine
 * install freshly compiled target/gerrit-trigger.hpi from above on my Windows Jenkins server
 * import 3 jobs triggering on changes in my usual repo on my usual Gerrit server 
 * upload a change to my Gerrit server
 * observe that all 3 jobs are triggered properly in my Windows Jenkins server
 * observe that all 3 'Build Started" message are posted properly as comments in the Gerrit review
 * observe that the verify +1 verdict is posted properly in the Gerrit review.

@rsandell can you please consider merging that PL then?

**Comment by dsariel** [comment]
any news re this PR?

**Pull request merged**
