### PR TITLE
[JENKINS-69059] Fix dynamic configuration cache proxy

### PR DESCRIPTION
**Pull request by ckreisl**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Stacktrace from Jenkins log:

```Timer task GerritTriggerTimerTask{job='foobar'} failed
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1469)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1493)
    at com.sonyericsson.hudson.plugins.gerrit.trigger.hudsontrigger.DynamicConfigurationCacheProxy.fetchThroughCache(DynamicConfigurationCacheProxy.java:44)
    at com.sonyericsson.hudson.plugins.gerrit.trigger.hudsontrigger.GerritTrigger.updateTriggerConfigURL(GerritTrigger.java:1931)
    at com.sonyericsson.hudson.plugins.gerrit.trigger.hudsontrigger.GerritTriggerTimerTask.doRun(GerritTriggerTimerTask.java:63)
    at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:92)
    at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:750)
```

We doubt that [JENKINS-68181](https://issues.jenkins.io/browse/JENKINS-68181) was completely fixed with the PR #463 which introduced `SafeTimerTask`. The problem we identified is coming from these lines of code:

```
synchronized List<GerritProject> fetchThroughCache(String url) throws IOException, ParseException {
        if (cache.containsKey(url) && !isExpired(url)) {
            logger.debug("Get dynamic projects from cache for URL: " + url);
            // Maintain cache while not fetching from URL
            for (String keyUrl : ttl.keySet()) {
               if (isExpired(keyUrl)) {
                   ttl.remove(keyUrl);
                   cache.remove(keyUrl);
                   logger.trace("Removing {} from cache", keyUrl);
               }
            }

            return cache.get(url);
        }
```
Iterating over a the `keySet()` while deleting items lead to the `ConcurrentModificationException` which is not catched in the big try and catch block of `GerritTrigger.java` line [GerritTrigger.java:1931](https://github.com/jenkinsci/gerrit-trigger-plugin/blob/master/src/main/java/com/sonyericsson/hudson/plugins/gerrit/trigger/hudsontrigger/GerritTrigger.java#L1931).

Example code tested here: [https://www.jdoodle.com/online-java-compiler/](https://www.jdoodle.com/online-java-compiler/)
throws the expected Exception.
```
import java.util.HashMap;
import java.util.Map;

public class MyClass {
    public static void main(String args[]) {

        Map<String, String> map = new HashMap<>();
        map.put("foo", "bar");
        map.put("bar", "foo");
        
        for(String keyUrl : map.keySet()) {
            if(keyUrl == "bar") {
                map.remove(keyUrl);
            }
        }

    }
}
```

We introduced two new classes `Cache` and `CacheEntry` and replaced the for loop by using the `Iterator` class. In addition we introduced `synchronized` on the cache object. 

Last thing I wanted to check on are proper Unit Tests since the ones available for this class doesn't seem to be that stable, but I could be wrong ;)

### CODE REVIEW

**Comment by ckreisl** [comment]
@rsandell fyi.

**Comment by rsandell** [comment]
Instead of trying to fix the issue by reinventing the wheel, perhaps it would be wiser to use something like https://github.com/jenkinsci/caffeine-api-plugin ?

**Comment by rsandell** [comment]
Sorry for not seeing this PR until now, for some reason it was marked as read for me so I didn't pay enough attention when browsing through what needed my attention.

**Comment by ckreisl** [comment]
> Instead of trying to fix the issue by reinventing the wheel, perhaps it would be wiser to use something like https://github.com/jenkinsci/caffeine-api-plugin ?

ok, thanks for the feedback. I'll check on that and keep you posted.

> Sorry for not seeing this PR until now, for some reason it was marked as read for me so I didn't pay enough attention when browsing through what needed my attention.

No problem, already happy that you guys pushed it to Java 11.

**Comment by ckreisl** [comment]
Will need some rework based on the latest changes.

**Pull request closed without merging**
