### PR TITLE
Fix Config Page Auth validation

### PR DESCRIPTION
**Pull request by scoheb**
This fixes a problem whereby Test Connection (SSH and REST) fails
AFTER you have saved and re-loaded the config page.

[FIXED JENKINS-30370]

### CODE REVIEW

**Comment by scoheb** [comment]
I do not see this one mentioned in the release notes.

**Comment by rsandell** [comment]
2.17.5 released today, maybe the wiki cache isn't refreshed for you?

**Comment by scoheb** [comment]
I realized that after I wrote the comment :)

tx

**Comment by scoheb** [comment]
Actually https://github.com/jenkinsci/gerrit-trigger-plugin/pull/260 is not mentioned in release notes.

**Comment by rsandell** [comment]
Oops, fixed :)

**Pull request merged**
