### PR TITLE
Add a trigger for comment containing a specified RegEx

### PR DESCRIPTION
**Pull request by dopuskh3**
This patch add a trigger that will trigger jenkins build on comment containing
a specified regular expression.

This can be usefull for user to specify a comment to run a build (eg.  Please test this )

### CODE REVIEW

**Comment by sskotha** [comment]
I am using the version 2.23.0, is this feature available? I couldn't figure out how to use it, but it would be very useful.

**Comment by rsandell** [comment]
@sskotha This PR was merged on Aug 26, 2014.

**Comment by sskotha** [comment]
Thanks, @rsandell . I couldn't find clear documentation on how to use this (Or I am not smart enough to figure it out). Could you tell me how to use it, or point me to a good documentation? I couldn't figure it out from what's written in https://wiki.jenkins-ci.org/display/JENKINS/Gerrit+Trigger

**Comment by sskotha** [comment]
@rsandell sorry, never mind... I didn't look enough.

**Pull request merged**
