### PR TITLE
Fix current patchset only

### PR DESCRIPTION
**Pull request by oharboe**
Split #230 into multiple commits to make it more readable/reviewable.

Perhaps we could use mockito to write JUnit some tests here?

### CODE REVIEW

**Comment by scoheb** [comment]
Hi,

I am back in at work on Tuesday (Monday is a holiday in Canada). I can work on tests then.

Thanks

Scott

**Comment by rsandell** [comment]
Have you analyzed the test failures?

**Comment by oharboe** [comment]
No.

I guess I'm misusing pull requests a bit, as I'm accustomed to Gerrit where
one uses reviews to share progress with other developers.

Sorry about the noise.

On Mon, May 18, 2015 at 11:49 AM, Robert Sandell <notifications@github.com>
wrote:

> Have you analyzed the test failures?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jenkinsci/gerrit-trigger-plugin/pull/231#issuecomment-102998768>
> .
>



-- 
Øyvind Harboe - Can Zylin Consulting help on your project?
http://www.zylin.com/

**Comment by rsandell** [comment]
So you don't intend for this to be merged?

**Comment by oharboe** [comment]
Not yet anyway.

**Pull request closed without merging**
