### PR TITLE
Add autogenerated prefix to the jenkins-gerrit-trigger tag

### PR DESCRIPTION
**Pull request by davido**
This is needed for the comments to be recognized as bot comments on
the Gerrit UI side, see: [1] for more details and the current code: [2].

[1] https://bugs.chromium.org/p/gerrit/issues/detail?id=6357
[2] https://gerrit.googlesource.com/gerrit/+/master/polygerrit-ui/app/elements/change/gr-message/gr-message.js#173

### CODE REVIEW

**Comment by gertvdijk** [comment]
Looks OK, cool! (Only nit is commit message typo)

**Comment by davido** [comment]
>  (Only nit is commit message typo)

Yes, noticed it, just wonder, how can I edit commit message on GitHub in browser?

**Comment by gertvdijk** [comment]
> how can I edit commit message on GitHub in browser?

Last time I checked, GitHub (and siblings) are plain ignorant about commit messages. I couldn't even comment on it. :man_shrugging:

**Comment by davido** [comment]
> Last time I checked, GitHub (and siblings) are plain ignorant about commit messages. I couldn't even comment on it.

Yeah, in Gerrit I could so that ;-)

**Comment by davido** [comment]
> (Only nit is commit message typo)

Should be fixed now. Done.

**Comment by vlotorev** [comment]
Hi, any chance to release plugin so Jenkins could be updated with this functionality? Without this pull request new PolyGerrit UI on 2.15 doesn't filter out Jenkins comments, so users have to use GWT old UI for now.

**Comment by gertvdijk** [comment]
@vlotorev You just posted this in the context of a pull request — I suggest to file an issue in the Jenkins issue tracker (component `gerrit-trigger-plugin`, project 'Jenkins') to request a release instead. Perhaps cc `rsandell` there.

**Comment by vlotorev** [comment]
@gertvdijk , done, https://issues.jenkins-ci.org/browse/JENKINS-53075
Thanks for replying.

**Pull request merged**
