### PR TITLE
operator '^' for dynamic trigger must be escaped in regex

### PR DESCRIPTION
**Pull request by mbudnick**
If you use "Dynamic Trigger Configuration" with line "b^**" there will be an exception "cannot parse" in GerritDynamicUrlProcessor line 154.
Operator "^" must be escaped if used in regex pattern.

### CODE REVIEW

**Comment by rsandell** [comment]
Could you provide a unit test?

**Comment by mbudnick** [comment]
I never wrote tests with mockito and powermock, I use jmockit. So I don't know how to mock url.openConnection() or test private methods.
There are also errors in test-classes and pom.xml when I import the project in my Eclipse and tests don't run.
So I can't provide a unit test.

**Comment by rsandell** [comment]
You don't need to do any of that mocking or url connection stuff. Just copy and slightly modify this one https://github.com/jenkinsci/gerrit-trigger-plugin/blob/master/src/test/java/com/sonyericsson/hudson/plugins/gerrit/trigger/spec/SpecGerritTriggerHudsonTest.java#L217
And you can run `mvn test -Dtest=SpecGerritTriggerHudsonTest` on the commandline to verify.

**Comment by mbudnick** [comment]
I wrote a unit test for "b^**" (which was my problem). How can I add this to this pull request? Should I amend my first commit to include the test?

**Comment by rsandell** [comment]
Just push a new commit to `mbudnick:master` no need to ammend

**Comment by rsandell** [comment]
Thanks!

**Pull request merged**
